runtime: nodejs18

# for cloud-SQL mysql config
# env_variables:
#   user: process.env.DB_USER, // e.g. 'my-db-user'
#   password: process.env.DB_PASS, // e.g. 'my-db-password'
#   database: process.env.DB_NAME, // e.g. 'my-database'
#   socketPath: process.env.INSTANCE_UNIX_SOCKET, // e.g. '/cloudsql/project:region:instance'

env_variables:
  user: process.env.DB_USER
  database: process.env.DB_NAME
  socketPath: process.env.INSTANCE_UNIX_SOCKET
